### ISSUE TITLE
BOOLEAN data type is not supported

### ISSUE THREAD

**Issue by 2-5** [duckdb/sqlite_scanner#53] opened 2023-06-18 21:41 UTC
### What happens?

I have SQLite databases with `BOOLEAN` columns and I can't read data from them using DuckDB and `ATTACH` because I get `duckdb.TypeMismatchException` exceptions.

### To Reproduce

```python
import os
import sqlite3

import duckdb

def create_sqlite(filename):
    if os.path.isfile(filename):
        os.remove(filename)

    conn = sqlite3.connect(filename)
    cur = conn.cursor()

    cur.execute("CREATE TABLE entry(id INTEGER, is_active BOOLEAN)")
    cur.execute("INSERT INTO entry VALUES (44, FALSE), (55, TRUE)")
    conn.commit()

    for row in cur.execute("SELECT * FROM entry"):
        print(row)
    print()

def attach_sqlite(filename):
    conn = duckdb.connect()
    conn.execute(f"ATTACH '{filename}' AS sqlite (TYPE SQLITE)")

    query = "SELECT name, type FROM pragma_table_info('sqlite.entry')"
    for column_name, column_type in conn.execute(query).fetchall():
        print(f"{column_name} {column_type}")
    print()

    print(conn.sql("SELECT * FROM sqlite.entry"))

filename = "test_sqlite_boolean.sqlite"
create_sqlite(filename)
attach_sqlite(filename)
```

Output:

```python
(44, 0)
(55, 1)

id BIGINT
is_active VARCHAR

Traceback (most recent call last):
  File "test_sqlite_boolean.py", line 30, in <module>
    attach_sqlite(filename)
  File "test_sqlite_boolean.py", line 26, in attach_sqlite
    print(conn.sql("SELECT * FROM sqlite.entry"))
duckdb.TypeMismatchException:
Mismatch Type Error: Invalid type in column "is_active":
column was declared as text, found "0" of type "integer" instead.
```

### OS:

Windows 10 x64

### SQLite Version:

3.38.4

### DuckDB Version:

0.8.1

### DuckDB Client:

Python 3.11

### Full Name:

2-5

### Affiliation:

2-5

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Mause** [comment] 2023-06-19 02:04
The issue here is that SQLite doesn't actually have a BOOLEAN type - it just blindly accepts whatever type name you give it, and allows any data type in column type. To work around this issue with columns with bad data, we have a `sqlite_all_varchar` setting.

You can read more here: https://duckdb.org/docs/extensions/sqlite_scanner#data-types

**Comment by 2-5** [comment] 2023-06-19 09:53
@Mause 

I did try `sqlite_all_varchar` before opening this issue, the exact same error is returned. `sqlite_all_varchar` forces treatment of all columns as `VARCHAR`, but that is exactly the problem here, that the `BOOLEAN` column is treated as `VARCHAR`.

`BOOLEAN` is a recognized SQLite type alias, see [3.1.1. Affinity Name Examples](https://www.sqlite.org/datatype3.html#affinity_name_examples)

The root cause is the type mapping used by DuckDB SQLite extension described on the page you linked. There needs to be an extra step before bailing out to `VARCHAR`:

**7. If the declared type is “BOOLEAN”, then it is translated into `BIGINT`**
8. If none of the above apply, then it is translated into VARCHAR.

**Comment by Mause** [comment] 2023-06-21 05:42
Okay, it looks like this is partially a duplicate of #47, and partially a feature request for boolean type support then

**Comment by Mause** [comment] 2023-06-21 05:46
For the time being, using the older style attach method works:

```python
import os
import sqlite3

import duckdb

def create_sqlite(filename):
    if os.path.isfile(filename):
        os.remove(filename)

    conn = sqlite3.connect(filename)
    cur = conn.cursor()

    cur.execute("CREATE TABLE entry(id INTEGER, is_active BOOLEAN)")
    cur.execute("INSERT INTO entry VALUES (44, FALSE), (55, TRUE)")
    conn.commit()

    for row in cur.execute("SELECT * FROM entry"):
        print(row)
    print()

def attach_sqlite(filename):
    conn = duckdb.connect()
    conn.install_extension('sqlite')
    conn.load_extension('sqlite')
    conn.execute('set global sqlite_all_varchar = True')
    conn.execute(f"CALL sqlite_attach('{filename}');")
    print(conn.sql("SELECT * FROM memory.entry"))

filename = "test_sqlite_boolean.sqlite"
create_sqlite(filename)
attach_sqlite(filename)
```

**Comment by 2-5** [comment] 2023-06-21 10:14
SQLite, if it doesn't recognize the column type, [defaults](https://www.sqlite.org/datatype3.html#determination_of_column_affinity) to `NUMERIC` (basically same thing as `INTEGER`):

> 5. Otherwise, the affinity is NUMERIC.

DuckDB SQLite scanner however [defaults](https://duckdb.org/docs/extensions/sqlite_scanner#data-types) to `VARCHAR`:

> 7. If none of the above apply, then it is translated into VARCHAR.

It seems this mismatch will continue to cause issues in the future. Maybe DuckDB SQLite scanner should use the same `INTEGER` default type as SQLite.

A workaround might be adding two new options, which force the datatype for unknown columns, (instead of all columns like `sqlite_all_varchar`):

- `sqlite_unknown_varchar`
- `sqlite_unknown_numeric`

**Closed** 2023-10-19 10:36 UTC
